# HTTP Server
server:
  port: 8081   # HTTP (Tomcat) port

# Spring properties
spring:
  application:
    name: wynats-configuration-api

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 



