# Spring properties
spring:
  application:
     name: wynats-configuration-api

# Discovery Server Access
eureka:
  instance:
    prefer-ip-address: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
        

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
  servlet:
    contextPath: /wynats-configuration-api
