# Spring properties
spring:
  application:
     name: wynats-configuration-api

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

# HTTP Server
server:
  port: 8081   # HTTP (Tomcat) port
  servlet:
    contextPath: /wynats-configuration-api
